# Generated by Django 5.0.3 on 2025-04-22 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abstract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pubmed_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("abstract_text", models.TextField()),
                ("journal", models.CharField(max_length=255)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="EntityCanonicalGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField()),
                ("propositions_paragraph", models.TextField(blank=True, null=True)),
                ("coreferenced_paragraph", models.TextField(blank=True, null=True)),
                ("natural_language_paragraph", models.TextField(blank=True, null=True)),
                ("propositions_similarity", models.FloatField(blank=True, null=True)),
                ("coreferenced_similarity", models.FloatField(blank=True, null=True)),
                (
                    "natural_language_similarity",
                    models.FloatField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntityAlias",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "canonical_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="knowledge_graph_generator.entitycanonicalgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InferredQuadruple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=255)),
                ("subject_types", models.JSONField(default=list)),
                ("predicate", models.CharField(max_length=255)),
                ("predicate_types", models.JSONField(default=list)),
                ("object_name", models.CharField(max_length=255)),
                ("object_types", models.JSONField(default=list)),
                ("reason", models.TextField()),
                ("natural_language_sentence", models.TextField(blank=True, null=True)),
                (
                    "paragraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inferred_quadruples",
                        to="knowledge_graph_generator.paragraph",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("coreferenced_text", models.TextField(blank=True, null=True)),
                (
                    "paragraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propositions",
                        to="knowledge_graph_generator.paragraph",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quadruple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=255)),
                ("subject_types", models.JSONField(default=list)),
                ("predicate", models.CharField(max_length=255)),
                ("predicate_types", models.JSONField(default=list)),
                ("object_name", models.CharField(max_length=255)),
                ("object_types", models.JSONField(default=list)),
                ("reason", models.TextField()),
                ("natural_language_sentence", models.TextField(blank=True, null=True)),
                ("cosine_similarity", models.FloatField(blank=True, null=True)),
                ("question", models.TextField(blank=True, null=True)),
                ("answer_to_question", models.TextField(blank=True, null=True)),
                ("answer_similarity", models.FloatField(blank=True, null=True)),
                (
                    "paragraph",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quadruples",
                        to="knowledge_graph_generator.paragraph",
                    ),
                ),
                (
                    "proposition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quadruples",
                        to="knowledge_graph_generator.proposition",
                    ),
                ),
            ],
        ),
    ]
