# Generated by Django 5.0.3 on 2025-05-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_graph_generator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StagedQuadruple",
            fields=[
                (
                    "quadruple_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("subject_name", models.CharField(max_length=255)),
                ("subject_types", models.JSONField(blank=True, default=list)),
                ("subject_is_ontological", models.BooleanField(default=False)),
                ("predicate", models.CharField(max_length=255)),
                ("predicate_types", models.JSONField(blank=True, default=list)),
                ("object_name", models.CharField(max_length=255)),
                ("object_types", models.JSONField(blank=True, default=list)),
                ("object_is_ontological", models.BooleanField(default=False)),
                ("context_paragraph", models.TextField()),
                ("proposition_sentence", models.TextField()),
                ("coreference_sentence", models.TextField(blank=True, null=True)),
                ("natural_language_sentence", models.TextField(blank=True, null=True)),
                ("inferred", models.BooleanField(default=False)),
                (
                    "paragraph",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staged_quadruples",
                        to="knowledge_graph_generator.paragraph",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
