# Generated by Django 5.0.3 on 2025-05-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_graph_generator", "0002_stagedquadruple"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stagedquadruple",
            name="context_paragraph",
        ),
        migrations.AddField(
            model_name="stagedquadruple",
            name="context_sentence",
            field=models.TextField(blank=True, null=True),
        ),
    ]
