# Generated by Django 5.0.3 on 2025-05-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "knowledge_graph_generator",
            "0003_remove_stagedquadruple_context_paragraph_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inferredquadruple",
            name="question",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stagedquadruple",
            name="question",
            field=models.TextField(blank=True, null=True),
        ),
    ]
