# Generated by Django 5.0.3 on 2025-05-22 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "knowledge_graph_generator",
            "0004_inferredquadruple_question_stagedquadruple_question",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stagedquadruple",
            name="paragraph",
        ),
        migrations.CreateModel(
            name="StagingParagraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="pubmedqa-context", max_length=50)),
                ("pushed_to_graph", models.BooleanField(default=False)),
                (
                    "push_target",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paragraph",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staging_meta",
                        to="knowledge_graph_generator.paragraph",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stagedquadruple",
            name="staging_paragraph",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL only for rows created prior to the staging-paragraph migration.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quadruples",
                to="knowledge_graph_generator.stagingparagraph",
            ),
        ),
        migrations.AddIndex(
            model_name="stagingparagraph",
            index=models.Index(
                fields=["pushed_to_graph", "created_at"],
                name="knowledge_g_pushed__d1d428_idx",
            ),
        ),
    ]
