# graph_algorithm/llm_answer.py
# ═════════════════════════════
"""
LLM helpers for ALG-GraphRAG
----------------------------

1) `aggregate_paragraph(question, outline)`
      • outline = the *combined* multi-graph string generated by
        `render_outline_3A` (or several such strings concatenated).
      • The assistant must ONLY rely on sentences that start with the
        glyph '▸'.  The resulting answer is a single concise paragraph.

2) `classify_yes_no_maybe(question, answer)`
      • Converts the paragraph into {'decision': 'yes'|'no'|'maybe'}.

3) `generate_answer(question, outline)`
      • Convenience wrapper → (paragraph, decision)

All three functions are synchronous, stateless, and isolated – the calling
management-command keeps responsibility for caching / rate-limits, etc.
"""

from __future__ import annotations

import json
from typing import Tuple, Literal

from openai import OpenAI
from pydantic import BaseModel, Field, ValidationError

from django.conf import settings
from openai import OpenAI

# ── OpenAI client ---------------------------------------------------
MODEL_NAME     = "gpt-4.1-nano"
_client = OpenAI(api_key=settings.OPENAI_API_KEY)


# ────────────────────────────────────────────────────────────────
# 1.  AGGREGATOR  (outline → paragraph)
# ────────────────────────────────────────────────────────────────
def aggregate_paragraph(
    question: str,
    outline: str,
) -> str:
    """
    Combine the *proposition sentences* (marked with ▸) into
    a single, coherent paragraph that answers the question.

    • The assistant may NOT introduce outside knowledge.
    • Every fact used **must** originate from a ▸-line.
    """
    system = (
        "You are a biomedical QA assistant.\n"
        "You will receive a question and a set of knowledge-graph outlines.\n"
        "Each factual proposition is prefixed with the glyph '▸'.\n"
        "Write ONE concise paragraph that answers the question *solely* "
        "by weaving together the relevant ▸‐propositions. "
        "Do NOT add any other information, speculation, or bias.\n"
    )

    user_block = json.dumps(
        {
            "question": question,
            "outline": outline,
            "instructions": (
                "Use ONLY the ▸ lines.   "
                "Do NOT quote the glyphs in your answer. "
                "A short paragraph (≈4-6 sentences) is enough."
            ),
        },
        indent=2,
    )

    resp = _client.chat.completions.create(
        model=MODEL_NAME,
        temperature=0.0,
        messages=[
            {"role": "system", "content": system},
            {"role": "user",   "content": user_block},
        ],
    )
    return resp.choices[0].message.content.strip()


# ────────────────────────────────────────────────────────────────
# 2.  DECIDER  (paragraph → yes / no / maybe)
# ────────────────────────────────────────────────────────────────
class _Decision(BaseModel):
    decision: Literal["yes", "no", "maybe"] = Field(
        ..., description="'yes', 'no', or 'maybe'"
    )


def classify_yes_no_maybe(question: str, answer: str) -> str:
    """
    Return one of: **yes / no / maybe**

    Robust JSON parsing with a fallback to 'maybe' on LLM hiccups.
    """
    sys_prompt = (
        "Return ONLY a JSON object {'decision': 'yes'|'no'|'maybe'} indicating "
        "whether the answer implies YES, NO, or MAYBE to the question."
    )
    user_json = json.dumps({"question": question, "answer": answer}, indent=2)

    resp = _client.chat.completions.create(
        model=MODEL_NAME,
        temperature=0.0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": sys_prompt},
            {"role": "user",   "content": user_json},
        ],
    )

    raw = resp.choices[0].message.content
    try:
        return _Decision.model_validate_json(raw).decision
    except (ValidationError, json.JSONDecodeError):
        # last-ditch attempt
        try:
            return json.loads(raw).get("decision", "maybe")
        except Exception:  # still malformed
            return "maybe"




# ────────────────────────────────────────────────────────────────
# 3.  Convenience wrapper
# ────────────────────────────────────────────────────────────────
def generate_answer(
    question: str,
    outline: str,
) -> Tuple[str, str]:
    """
    Returns
    -------
    (paragraph, decision)
        paragraph : str   – aggregated answer (no ▸ glyphs)
        decision  : str   – 'yes' | 'no' | 'maybe'
    """
    paragraph = aggregate_paragraph(question, outline)
    decision  = classify_yes_no_maybe(question, paragraph)
    return paragraph, decision