# Generated by Django 5.0.3 on 2025-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphrag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
