"""
Tree-of-Thought ⇄ GraphRAG engine
═════════════════════════════════
**Purpose**

Run the ToT pipeline twice:

1. **Original question** – full sibling-queue DFS search.
2. **Null-hypothesis re-write** – the same search on the negated version
   of the question (generated by a small Rewriter agent).

Each run produces its own tree image, bundles, and Aggregator essay.
The function then:

* saves the two SVG/PNG files with a **shared timestamp** so they sort
  together, e.g.  
  `2025-06-29T14-06-12_orig_tot.png` and
  `2025-06-29T14-06-12_null_tot.png`;
* builds a single **combined markdown answer** that includes both
  questions explicitly, so legacy callers can still do  
  `result["aggregate"]["response"]`.

The full result object also exposes everything separately under
`result["original"]` and `result["null"]` for richer UIs.

Traversal strategy (inside one run)
-----------------------------------
* **Depth-first** down the *first* plan of every node.
* All sibling plans are queued FIFO, giving a *breadth* effect across
  the search space.
* At the depth ceiling we *still* run a Questioner + GraphRAG cycle, so
  every visible leaf ends in a Q/A pair.

Key functions
~~~~~~~~~~~~~
* `_dfs_path`   – one DFS path, queues siblings  
* `_search_tree` – pops that queue until exhausted / budget hit  
* `_null_question` – calls the Rewriter agent  
* `_aggregate_step` – calls the Aggregator agent  
* `run_tot`     – public façade: orchestrates two runs and ties
  everything together
"""

from __future__ import annotations

import json, sys
from collections import deque
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

from openai import OpenAI

from . import config, prompts, schemas, utils, visualize
# from graphrag.graphrag_agent.wrapper import answer_question
from .self_answer import dummy_answer_question as answer_question

CLIENT = OpenAI(api_key=config.OPENAI_API_KEY)

# ═══════════════════════ Agent call helper ════════════════════════════════
def _parse(model: str, system: str, ctx: List[str], schema, max_out: int):
    """Convenience wrapper for JSON-schema chat completions."""
    return (
        CLIENT.beta.chat.completions.parse(
            model=model,
            max_tokens=max_out,
            messages=[
                {"role": "system", "content": system},
                {"role": "user",   "content": "\n".join(ctx)},
            ],
            response_format=schema,
        ).choices[0].message.parsed
    )

# ═══════════════════════ Bundle helper ════════════════════════════════════
def _bundle_trace(
    trace_ctx: List[str],
    node: str,
    bundles: List[Dict[str, Any]],
    answer_txt: str,
    stats: Dict[str, int],
) -> None:
    """Append a synthetic bundle when a branch stops prematurely."""
    synthetic = trace_ctx + [f"FINAL ANSWER {node or 'root'}: {answer_txt}"]
    bundle = _parse(
        config.MODEL, prompts.BUNDLE_SYS, synthetic, schemas.Bundle, max_out=512
    ).model_dump()
    bundles.append(bundle)
    stats["bundles"] += 1

# ═══════════════════════ Queue work-item ═══════════════════════════════════
@dataclass
class _Work:
    ctx: List[str]
    depth: int
    node_id: str
    parent_children: Dict[str, Any]
    plan_id: str

# ═══════════════════════ DFS path (depth-first) ════════════════════════════
def _dfs_path(
    ctx: List[str],
    depth: int,
    node: str,
    *,
    max_depth: int,
    max_children: int,
    max_answers: int,
    bundles: List[Dict[str, Any]],
    stats: Dict[str, int],
    root_question: str,
    queue: deque[_Work],
) -> Dict[str, Any]:
    """Follow **one** DFS path; enqueue siblings for later."""
    if len(bundles) >= max_answers:
        return {"answer": None, "trace": ctx + ["[stopped: max answers]"], "children": {}}

    # 1. Narrator / Reasoner
    ntr = _parse(config.MODEL, prompts.NARRATOR_SYS, ctx, schemas.NarratorTurn, 1024)
    utils.pretty_print(depth, "💭", ntr.narrative.replace("\n", " "))
    nxt = ctx + [f"NARRATIVE {node}.{depth}: {ntr.narrative}"]

    if ntr.action == "final":
        final = " ".join((ntr.final_answer or "").splitlines())
        utils.pretty_print(depth, "✅", final)
        nxt.append(f"FINAL ANSWER {node}: {final}")
        bundles.append(_parse(config.MODEL, prompts.BUNDLE_SYS, nxt, schemas.Bundle, 512).model_dump())
        stats["answers"] += 1; stats["bundles"] += 1
        return {"answer": final, "trace": nxt, "children": {}}

    # 2. Rumsfeld matrix
    rms = _parse(config.MODEL, prompts.RUMSFELD_SYS, nxt, schemas.RumsfeldTurn, 512)
    rms_line = f"RUMSFELD {node}.{depth}: KNOWN[{'; '.join(rms.knowns) or '(none)'}] | UNKNOWN[{'; '.join(rms.unknowns) or '(none)'}]"
    utils.pretty_print(depth, "📋", rms_line.replace(f'RUMSFELD {node}.{depth}: ', ''))
    nxt.append(rms_line)

    # 3. Brancher
    br_sys = prompts.BRANCHER_SYS_TEMPLATE.format(max_children=max_children)
    br = _parse(config.MODEL, br_sys, nxt, schemas.BranchDecision, 1024)
    plans = ( [{"id":"0","plan":br.plan}]
              if br.branch == "single"
              else [{"id":str(i),"plan":p["plan"]} for i,p in enumerate(br.plans[:max_children])])
    utils.pretty_print(depth, "🔀", f"{br.branch} ({len(plans)})")

    trace_here = nxt + [f"BRANCH {node}: {br.branch}"]
    node_dict: Dict[str, Any] = {"answer": None, "trace": trace_here, "children": {}}

    for idx, bp in enumerate(plans):
        if len(bundles) >= max_answers:
            break
        plan_ctx = trace_here + [f"PLAN {node}.{bp['id']}: {bp['plan']}"]

        if idx == 0:  # immediate DFS step
            utils.pretty_print(depth+1, "📝", bp["plan"].replace("\n", " "))

            qturn = _parse(config.MODEL, prompts.QUESTIONER_SYS, plan_ctx, schemas.QuestionTurn, 128)
            utils.pretty_print(depth+1, "❓", qturn.question)
            plan_ctx.append(f"QUESTION {node}.{bp['id']}.0: {qturn.question}")

            #ans_raw = answer_question(qturn.question, root_question=root_question)
            ans_raw = answer_question(qturn.question)
            
            utils.pretty_print(depth+1, "💡", ans_raw)
            plan_ctx.append(f"ANSWER {node}.{bp['id']}.0: {ans_raw}")

            if depth + 1 >= max_depth:
                stop = f"[stopped: depth limit → {node}.{bp['id']}]"
                utils.pretty_print(depth+1, "⏹", "Depth limit reached")
                stats["depth_hits"] += 1
                _bundle_trace(plan_ctx+[stop], f"{node}.{bp['id']}", bundles,
                              "(no answer – depth limit)", stats)
                node_dict["children"][bp["id"]] = {"answer":None,"trace":plan_ctx+[stop],"children":{}}
            else:
                node_dict["children"][bp["id"]] = _dfs_path(
                    plan_ctx, depth+1, f"{node}.{bp['id']}",
                    max_depth=max_depth, max_children=max_children,
                    max_answers=max_answers, bundles=bundles, stats=stats,
                    root_question=root_question, queue=queue)
        else:  # queue sibling plans
            if depth < max_depth:
                queue.append(_Work(plan_ctx, depth+1, f"{node}.{bp['id']}",
                                   node_dict["children"], bp["id"]))

    return node_dict

# ═══════════════════════ Root driver (queue loop) ══════════════════════════
def _search_tree(
    question: str,
    *,
    max_depth: int,
    max_children: int,
    max_answers: int,
):
    """Run the sibling-queue DFS once, return (tree, bundles, stats)."""
    bundles: List[Dict[str, Any]] = []
    stats = {"answers":0, "depth_hits":0, "bundles":0}
    queue: deque[_Work] = deque()

    dummy_parent: Dict[str, Any] = {}
    queue.append(_Work([f"ORIGINAL QUESTION: {question}"], 0, "", dummy_parent, "root"))

    while queue and len(bundles) < max_answers:
        w = queue.popleft()
        subtree = _dfs_path(
            w.ctx, w.depth, w.node_id,
            max_depth=max_depth, max_children=max_children,
            max_answers=max_answers, bundles=bundles, stats=stats,
            root_question=question, queue=queue)
        w.parent_children[w.plan_id] = subtree

    return dummy_parent["root"], bundles, stats

# ═══════════════════════ Null-hypothesis helper ════════════════════════════
def _null_question(original: str) -> str:
    turn = _parse(
        config.MODEL,
        prompts.NULL_HYPOTHESIS_SYS,
        [f"QUESTION: {original}"],
        schemas.NullQuestionTurn,
        max_out=128,
    )
    return turn.null_question.strip()

# ═══════════════════════ Aggregator helper ════════════════════════════════
def _aggregate_step(question: str, bundles: List[Dict[str, Any]]) -> Dict[str, Any]:
    blob = json.dumps(bundles, indent=2)
    rsp = CLIENT.chat.completions.create(
        model=config.MODEL,
        max_tokens=512,
        temperature=0,
        messages=[
            {"role": "system", "content": prompts.AGGREGATOR_SYS},
            {"role": "user",   "content": f"ORIGINAL QUESTION:\n{question}"},
            {"role": "user",   "content": blob},
        ],
        response_format={"type":"json_object"},
    )
    return json.loads(rsp.choices[0].message.content)

# ═══════════════════════ Public façade ════════════════════════════════════
def run_tot(
    question: str,
    *,
    max_depth: int | None = None,
    max_branches: int | None = None,
    max_answers: int | None = None,
) -> Dict[str, Any]:
    """Top-level entry: run the engine on *question* and its null variant."""
    depth    = max_depth    or config.MAX_DEPTH
    branches = max_branches or config.MAX_BRANCHES
    answers  = max_answers  or config.MAX_ANSWERS

    # 1. Derive the null-hypothesis question
    null_q = _null_question(question)
    print(f"\n🤔 NULL-hypothesis: {null_q}\n")

    # 2. Two independent ToT runs
    orig_tree, orig_bundles, orig_stats = _search_tree(
        question, max_depth=depth, max_children=branches, max_answers=answers)
    null_tree, null_bundles, null_stats = _search_tree(
        null_q,    max_depth=depth, max_children=branches, max_answers=answers)

    # 3. Two independent aggregations
    orig_agg = _aggregate_step(question, orig_bundles) if orig_bundles else {"response":"(no data)"}
    null_agg = _aggregate_step(null_q,    null_bundles) if null_bundles else {"response":"(no data)"}

    # 4. Save two images with **shared timestamp**
    ts = datetime.utcnow().isoformat(timespec="seconds").replace(":", "-")

    img_orig = visualize.save_tree_image(orig_tree, bundles=orig_bundles, aggregate=orig_agg["response"])
    img_null = visualize.save_tree_image(null_tree, bundles=null_bundles, aggregate=null_agg["response"])

    img_orig_lab = img_orig.with_name(f"{ts}_orig_tot{img_orig.suffix}"); img_orig.rename(img_orig_lab)
    img_null_lab = img_null.with_name(f"{ts}_null_tot{img_null.suffix}"); img_null.rename(img_null_lab)

    # 5. Combined answer (keeps API stable)
    combined_agg = {
        "response":
        f"**Answer to the question:** {question}\n"
        f"{orig_agg['response']}\n\n"
        f"**Answer to the null-hypothesis of the question:** {null_q}\n"
        f"{null_agg['response']}"
    }

    return {
        "aggregate": combined_agg,
        "original": {
            "tree": orig_tree,
            "bundles": orig_bundles,
            "aggregate": orig_agg,
            "stats": orig_stats,
            "image": str(img_orig_lab),
        },
        "null": {
            "tree": null_tree,
            "bundles": null_bundles,
            "aggregate": null_agg,
            "stats": null_stats,
            "image": str(img_null_lab),
        },
    }

# ═══════════════════════ CLI quick-test ═══════════════════════════════════
if __name__ == "__main__":
    q_cli = " ".join(sys.argv[1:]) or \
        "Do elevated CRP levels predict worse COVID-19 prognosis?"
    out = run_tot(q_cli, max_depth=3, max_answers=8)
    print(json.dumps(out["aggregate"], indent=2))